//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedianStats.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string notifierText {
            get {
                return ((string)(this["notifierText"]));
            }
            set {
                this["notifierText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mousefix {
            get {
                return ((bool)(this["mousefix"]));
            }
            set {
                this["mousefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nopickup {
            get {
                return ((bool)(this["nopickup"]));
            }
            set {
                this["nopickup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool toggleShowItems {
            get {
                return ((bool)(this["toggleShowItems"]));
            }
            set {
                this["toggleShowItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool notifyEnabled {
            get {
                return ((bool)(this["notifyEnabled"]));
            }
            set {
                this["notifyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool notifySuperior {
            get {
                return ((bool)(this["notifySuperior"]));
            }
            set {
                this["notifySuperior"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alwaysRun {
            get {
                return ((bool)(this["alwaysRun"]));
            }
            set {
                this["alwaysRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<SoundList xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <Sounds>
    <Sound>
      <FilePath>resources/sound1.wav</FilePath>
      <Volume>0.15</Volume>
    </Sound>
    <Sound>
      <FilePath>resources/sound2.wav</FilePath>
      <Volume>0.15</Volume>
    </Sound>
    <Sound>
      <FilePath>resources/sound3.wav</FilePath>
      <Volume>0.15</Volume>
    </Sound>
    <Sound>
      <FilePath>resources/sound4.wav</FilePath>
      <Volume>0.15</Volume>
    </Sound>
    <Sound>
      <FilePath>resources/sound5.wav</FilePath>
      <Volume>0.15</Volume>
    </Sound>
  </Sounds>
</SoundList>")]
        public global::MedianStats.IO.SoundList notifierSounds {
            get {
                return ((global::MedianStats.IO.SoundList)(this["notifierSounds"]));
            }
            set {
                this["notifierSounds"] = value;
            }
        }
    }
}
